[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "g++", "curl"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python start.py" 